# Generated by Django 3.2.10 on 2022-06-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0004_auto_20220605_0505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
