# Generated by Django 3.2.10 on 2022-06-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0006_auto_20220606_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='created',
        ),
    ]
